# AI-META-BEGIN
# 
# AI-META: Build or utility script
# OWNERSHIP: scripts (build/deployment utilities)
# ENTRYPOINTS: Imported by application modules
# DEPENDENCIES: internal packages (@repo/*), HubSpot (CRM)
# DANGER: None identified
# CHANGE-SAFETY: Review impact on consumers before modifying public API
# TESTS: Run: pnpm test && pnpm type-check
# 
# AI-META-END

#!/bin/bash

###############################################################################
# Client Provisioning Script
# 
# Purpose: Automate the creation of a new client site from the template-site
# 
# Usage: ./provision-client.sh <client-name> [options]
#
# Options:
#   --theme-primary    Primary color for theme (hex)
#   --theme-secondary  Secondary color for theme (hex)
#   --skip-git        Skip git operations
#   --dry-run         Show what would be done without executing
#
# Example: ./provision-client.sh acme-corp --theme-primary "#FF5733"
###############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
CLIENT_NAME=""
THEME_PRIMARY="#0066CC"
THEME_SECONDARY="#00AA66"
SKIP_GIT=false
DRY_RUN=false
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --theme-primary)
            THEME_PRIMARY="$2"
            shift 2
            ;;
        --theme-secondary)
            THEME_SECONDARY="$2"
            shift 2
            ;;
        --skip-git)
            SKIP_GIT=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            if [[ -z "$CLIENT_NAME" ]]; then
                CLIENT_NAME="$1"
            else
                log_error "Unknown option: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

# Validate client name
if [[ -z "$CLIENT_NAME" ]]; then
    log_error "Client name is required"
    echo "Usage: $0 <client-name> [options]"
    exit 1
fi

# Validate client name format (lowercase with hyphens)
if [[ ! "$CLIENT_NAME" =~ ^[a-z0-9-]+$ ]]; then
    log_error "Client name must contain only lowercase letters, numbers, and hyphens"
    exit 1
fi

CLIENT_DIR="$REPO_ROOT/apps/$CLIENT_NAME"
TEMPLATE_DIR="$REPO_ROOT/apps/template-site"
THEME_DIR="$REPO_ROOT/packages/tokens/src/themes"

log_info "Starting client provisioning for: $CLIENT_NAME"
log_info "Repository root: $REPO_ROOT"

# Check if client already exists
if [[ -d "$CLIENT_DIR" ]]; then
    log_error "Client directory already exists: $CLIENT_DIR"
    exit 1
fi

# Check if template exists
if [[ ! -d "$TEMPLATE_DIR" ]]; then
    log_error "Template directory not found: $TEMPLATE_DIR"
    exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
    log_warning "DRY RUN MODE - No changes will be made"
    echo ""
    echo "Would perform the following operations:"
    echo "  1. Copy $TEMPLATE_DIR -> $CLIENT_DIR"
    echo "  2. Create theme configuration in $THEME_DIR/$CLIENT_NAME"
    echo "  3. Update package.json with client name"
    echo "  4. Update next.config.js"
    echo "  5. Create client-specific environment configuration"
    echo "  6. Update workspace configuration"
    exit 0
fi

log_info "Step 1: Copying template to new client directory..."
cp -r "$TEMPLATE_DIR" "$CLIENT_DIR"
log_success "Template copied successfully"

log_info "Step 2: Creating theme configuration..."
mkdir -p "$THEME_DIR/$CLIENT_NAME"

# Create theme configuration file
cat > "$THEME_DIR/$CLIENT_NAME/index.ts" << EOF
/**
 * Theme Configuration for $CLIENT_NAME
 * 
 * Auto-generated by provision-client.sh
 * Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
 */

export const ${CLIENT_NAME//-/_}Theme = {
  colors: {
    primary: '$THEME_PRIMARY',
    secondary: '$THEME_SECONDARY',
    // Add more theme colors as needed
  },
  typography: {
    fontFamily: 'system-ui, -apple-system, sans-serif',
    // Add typography settings
  },
  spacing: {
    // Add spacing overrides if needed
  },
} as const;

export default ${CLIENT_NAME//-/_}Theme;
EOF

log_success "Theme configuration created"

log_info "Step 3: Updating package.json..."
cd "$CLIENT_DIR"

# Update package.json with correct client name
if [[ -f "package.json" ]]; then
    # Use node to safely update JSON
    node -e "
    const fs = require('fs');
    const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    pkg.name = '@repo/$CLIENT_NAME';
    fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
    "
    log_success "package.json updated"
else
    log_warning "package.json not found in client directory"
fi

log_info "Step 4: Creating client-specific environment configuration..."
cat > ".env.example" << EOF
# $CLIENT_NAME Environment Configuration
# Copy this to .env.local for local development

# Site Configuration
NEXT_PUBLIC_SITE_NAME="$CLIENT_NAME"
NEXT_PUBLIC_SITE_URL="https://$CLIENT_NAME.example.com"

# Analytics (optional)
NEXT_PUBLIC_GA_ID=
NEXT_PUBLIC_GTM_ID=

# Integrations (optional)
NEXT_PUBLIC_HUBSPOT_PORTAL_ID=
NEXT_PUBLIC_HUBSPOT_FORM_ID=

# API Configuration
NEXT_PUBLIC_API_URL=
EOF

log_success "Environment configuration created"

log_info "Step 5: Creating client documentation..."
cat > "$CLIENT_DIR/README.md" << EOF
# $CLIENT_NAME

Client-specific site for $CLIENT_NAME.

## Setup

1. Copy \`.env.example\` to \`.env.local\`
2. Fill in required environment variables
3. Run \`pnpm install\` from the repository root
4. Run \`pnpm --filter @repo/$CLIENT_NAME dev\`

## Theme Customization

Theme configuration is located in:
\`packages/tokens/src/themes/$CLIENT_NAME/index.ts\`

## Deployment

See root documentation for deployment instructions.

---

**Provisioned**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Template**: template-site
EOF

log_success "Client documentation created"

# Return to repo root
cd "$REPO_ROOT"

log_info "Step 6: Updating workspace configuration..."
# Add to pnpm-workspace.yaml if needed (apps/* should already cover it)
log_success "Workspace configuration verified"

echo ""
log_success "✓ Client provisioning completed successfully!"
echo ""
echo "Next steps:"
echo "  1. Review and customize theme: $THEME_DIR/$CLIENT_NAME/index.ts"
echo "  2. Configure environment: $CLIENT_DIR/.env.local"
echo "  3. Customize content in: $CLIENT_DIR/app"
echo "  4. Run dev server: pnpm --filter @repo/$CLIENT_NAME dev"
echo ""
echo "Happy building! 🚀"
